INSERT INTO permissions (module, action, description) VALUES
  ('Cadastros', 'Visualizar', 'Visualizar cadastros (clientes, fornecedores, itens)'),
  ('Cadastros', 'Criar', 'Criar novos cadastros'),
  ('Cadastros', 'Editar', 'Editar cadastros existentes'),
  ('Cadastros', 'Excluir', 'Excluir cadastros'),
  ('Estoque', 'Visualizar', 'Visualizar itens e movimentações de estoque'),
  ('Estoque', 'Criar', 'Criar movimentações de estoque'),
  ('Estoque', 'Editar', 'Editar itens e grupos de estoque'),
  ('Estoque', 'Excluir', 'Excluir itens e movimentações'),
  ('Financeiro', 'Visualizar', 'Visualizar contas a pagar/receber e bancos'),
  ('Financeiro', 'Criar', 'Criar lançamentos financeiros'),
  ('Financeiro', 'Editar', 'Editar lançamentos financeiros'),
  ('Financeiro', 'Excluir', 'Excluir lançamentos financeiros'),
  ('Compras', 'Visualizar', 'Visualizar pedidos de compra e documentos de entrada'),
  ('Compras', 'Criar', 'Criar pedidos de compra e documentos de entrada'),
  ('Compras', 'Editar', 'Editar pedidos de compra'),
  ('Compras', 'Excluir', 'Excluir pedidos de compra'),
  ('Vendas', 'Visualizar', 'Visualizar orçamentos, pedidos de venda e documentos de saída'),
  ('Vendas', 'Criar', 'Criar orçamentos e pedidos de venda'),
  ('Vendas', 'Editar', 'Editar orçamentos e pedidos de venda'),
  ('Vendas', 'Excluir', 'Excluir orçamentos e pedidos de venda'),
  ('Serviços', 'Visualizar', 'Visualizar ordens de serviço e agenda'),
  ('Serviços', 'Criar', 'Criar ordens de serviço'),
  ('Serviços', 'Editar', 'Editar ordens de serviço'),
  ('Serviços', 'Excluir', 'Excluir ordens de serviço'),
  ('Controladoria', 'Visualizar', 'Visualizar DRE e fluxo de caixa'),
  ('Controladoria', 'Criar', 'Criar períodos contábeis'),
  ('Controladoria', 'Editar', 'Editar períodos contábeis'),
  ('Controladoria', 'Excluir', 'Fechar/excluir períodos contábeis'),
  ('Administração', 'Visualizar', 'Visualizar usuários e empresas'),
  ('Administração', 'Criar', 'Criar usuários'),
  ('Administração', 'Editar', 'Editar usuários e permissões'),
  ('Administração', 'Excluir', 'Excluir usuários');