
DO $$
DECLARE
  _tid uuid := '63fda2dc-1f37-4df4-b52f-a6385664c506';
BEGIN

INSERT INTO financial_natures (tenant_id, codigo, descricao, tipo, tipo_natureza, ordem, ativo) VALUES
(_tid, '1',     'RECEITAS',                    'SINTETICO', 'RECEITA', 100, true),
(_tid, '1.1',   'Receitas de Vendas',          'SINTETICO', 'RECEITA', 110, true),
(_tid, '1.1.1', 'Venda de Produtos',           'ANALITICO', 'RECEITA', 111, true),
(_tid, '1.1.2', 'Venda de Mercadorias',        'ANALITICO', 'RECEITA', 112, true),
(_tid, '1.2',   'Prestação de Serviços',       'SINTETICO', 'RECEITA', 120, true),
(_tid, '1.2.1', 'Receita de Serviços',         'ANALITICO', 'RECEITA', 121, true),
(_tid, '1.3',   'Receitas Financeiras',        'SINTETICO', 'RECEITA', 130, true),
(_tid, '1.3.1', 'Juros Recebidos',             'ANALITICO', 'RECEITA', 131, true),
(_tid, '1.3.2', 'Descontos Obtidos',           'ANALITICO', 'RECEITA', 132, true),
(_tid, '1.3.3', 'Rendimentos de Aplicações',   'ANALITICO', 'RECEITA', 133, true),
(_tid, '1.4',   'Outras Receitas',             'SINTETICO', 'RECEITA', 140, true),
(_tid, '1.4.1', 'Receitas Diversas',           'ANALITICO', 'RECEITA', 141, true),
(_tid, '2',     'CUSTOS VARIÁVEIS',            'SINTETICO', 'DESPESA', 200, true),
(_tid, '2.1',   'Custo dos Produtos Vendidos', 'SINTETICO', 'DESPESA', 210, true),
(_tid, '2.1.1', 'Matéria-prima',               'ANALITICO', 'DESPESA', 211, true),
(_tid, '2.1.2', 'Embalagens',                  'ANALITICO', 'DESPESA', 212, true),
(_tid, '2.2',   'Impostos sobre Vendas',       'SINTETICO', 'DESPESA', 220, true),
(_tid, '2.2.1', 'ICMS',                        'ANALITICO', 'DESPESA', 221, true),
(_tid, '2.2.2', 'PIS/COFINS',                  'ANALITICO', 'DESPESA', 222, true),
(_tid, '2.2.3', 'ISS',                         'ANALITICO', 'DESPESA', 223, true),
(_tid, '2.2.4', 'Simples Nacional',            'ANALITICO', 'DESPESA', 224, true),
(_tid, '2.3',   'Fretes sobre Vendas',         'SINTETICO', 'DESPESA', 230, true),
(_tid, '2.3.1', 'Frete de Entrega',            'ANALITICO', 'DESPESA', 231, true),
(_tid, '2.4',   'Comissões sobre Vendas',      'SINTETICO', 'DESPESA', 240, true),
(_tid, '2.4.1', 'Comissões de Vendedores',     'ANALITICO', 'DESPESA', 241, true),
(_tid, '2.4.2', 'Comissões de Representantes', 'ANALITICO', 'DESPESA', 242, true),
(_tid, '3',     'DESPESAS FIXAS',              'SINTETICO', 'DESPESA', 300, true),
(_tid, '3.1',   'Despesas com Pessoal',        'SINTETICO', 'DESPESA', 310, true),
(_tid, '3.1.1', 'Salários e Ordenados',        'ANALITICO', 'DESPESA', 311, true),
(_tid, '3.1.2', 'Encargos Sociais (INSS/FGTS)','ANALITICO', 'DESPESA', 312, true),
(_tid, '3.1.3', 'Vale Transporte',             'ANALITICO', 'DESPESA', 313, true),
(_tid, '3.1.4', 'Vale Alimentação/Refeição',   'ANALITICO', 'DESPESA', 314, true),
(_tid, '3.1.5', 'Plano de Saúde',             'ANALITICO', 'DESPESA', 315, true),
(_tid, '3.2',   'Despesas com Infraestrutura', 'SINTETICO', 'DESPESA', 320, true),
(_tid, '3.2.1', 'Aluguel de Imóvel',           'ANALITICO', 'DESPESA', 321, true),
(_tid, '3.2.2', 'Energia Elétrica',            'ANALITICO', 'DESPESA', 322, true),
(_tid, '3.2.3', 'Água e Esgoto',               'ANALITICO', 'DESPESA', 323, true),
(_tid, '3.2.4', 'Telefone e Internet',         'ANALITICO', 'DESPESA', 324, true),
(_tid, '3.2.5', 'Limpeza e Higiene',           'ANALITICO', 'DESPESA', 325, true),
(_tid, '3.3',   'Despesas Administrativas',    'SINTETICO', 'DESPESA', 330, true),
(_tid, '3.3.1', 'Software e Licenças',         'ANALITICO', 'DESPESA', 331, true),
(_tid, '3.3.2', 'Material de Escritório',      'ANALITICO', 'DESPESA', 332, true),
(_tid, '3.3.3', 'Contabilidade',               'ANALITICO', 'DESPESA', 333, true),
(_tid, '3.3.4', 'Serviços de Terceiros',       'ANALITICO', 'DESPESA', 334, true),
(_tid, '3.4',   'Despesas com Veículos',       'SINTETICO', 'DESPESA', 340, true),
(_tid, '3.4.1', 'Combustíveis',                'ANALITICO', 'DESPESA', 341, true),
(_tid, '3.4.2', 'Manutenção de Veículos',      'ANALITICO', 'DESPESA', 342, true),
(_tid, '3.4.3', 'Pedágio',                     'ANALITICO', 'DESPESA', 343, true),
(_tid, '3.5',   'Despesas com Alimentação',    'SINTETICO', 'DESPESA', 350, true),
(_tid, '3.5.1', 'Refeições e Lanches',         'ANALITICO', 'DESPESA', 351, true),
(_tid, '3.6',   'Marketing e Publicidade',     'SINTETICO', 'DESPESA', 360, true),
(_tid, '3.6.1', 'Propaganda e Marketing',      'ANALITICO', 'DESPESA', 361, true),
(_tid, '3.6.2', 'Anúncios Online',             'ANALITICO', 'DESPESA', 362, true),
(_tid, '4',     'DESPESAS COMERCIAIS',         'SINTETICO', 'DESPESA', 400, true),
(_tid, '4.1',   'Viagens e Deslocamentos',     'SINTETICO', 'DESPESA', 410, true),
(_tid, '4.1.1', 'Passagens Aéreas/Terrestres', 'ANALITICO', 'DESPESA', 411, true),
(_tid, '4.1.2', 'Hospedagem',                  'ANALITICO', 'DESPESA', 412, true),
(_tid, '4.1.3', 'Alimentação em Viagens',      'ANALITICO', 'DESPESA', 413, true),
(_tid, '4.2',   'Comissões Comerciais',        'SINTETICO', 'DESPESA', 420, true),
(_tid, '4.2.1', 'Comissões sobre Contratos',   'ANALITICO', 'DESPESA', 421, true),
(_tid, '5',     'INVESTIMENTOS E NÃO OPERACIONAL','SINTETICO','DESPESA', 500, true),
(_tid, '5.1',   'Investimentos em Ativos',     'SINTETICO', 'DESPESA', 510, true),
(_tid, '5.1.1', 'Compra de Equipamentos',      'ANALITICO', 'DESPESA', 511, true),
(_tid, '5.1.2', 'Compra de Móveis',            'ANALITICO', 'DESPESA', 512, true),
(_tid, '5.1.3', 'Compra de Veículos',          'ANALITICO', 'DESPESA', 513, true),
(_tid, '5.2',   'Despesas Financeiras',        'SINTETICO', 'DESPESA', 520, true),
(_tid, '5.2.1', 'Juros Pagos',                 'ANALITICO', 'DESPESA', 521, true),
(_tid, '5.2.2', 'Multas e Encargos',           'ANALITICO', 'DESPESA', 522, true),
(_tid, '5.2.3', 'Taxas Bancárias',             'ANALITICO', 'DESPESA', 523, true),
(_tid, '5.3',   'Empréstimos e Financiamentos','SINTETICO', 'DESPESA', 530, true),
(_tid, '5.3.1', 'Parcelas de Empréstimos',     'ANALITICO', 'DESPESA', 531, true),
(_tid, '5.3.2', 'Parcelas de Financiamentos',  'ANALITICO', 'DESPESA', 532, true);

END $$;
